
import { jsPDF } from 'jspdf';
import { ResearchPaper } from '../types';

export const generatePDF = (paper: ResearchPaper) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const textWidth = pageWidth - (margin * 2);
  let y = 30;

  const checkPage = (addedHeight: number) => {
    if (y + addedHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Main Heading wrapping
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  const mainTitle = "HISTORICAL RESEARCH FINDINGS";
  const mainTitleLines = doc.splitTextToSize(mainTitle, textWidth);
  doc.text(mainTitleLines, margin, y);
  // Calculate height: ~8mm per line for 22pt font
  y += (mainTitleLines.length * 10);
  
  // Sub-heading (Paper Title) wrapping
  doc.setFontSize(16);
  doc.setTextColor(180, 140, 20);
  const subTitle = paper.title.toUpperCase();
  const subTitleLines = doc.splitTextToSize(subTitle, textWidth);
  checkPage(subTitleLines.length * 8);
  doc.text(subTitleLines, margin, y);
  // Calculate height: ~7mm per line for 16pt font
  y += (subTitleLines.length * 8) + 2;
  
  // Decorative line
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  
  const lines = doc.splitTextToSize(paper.content, textWidth);
  lines.forEach((line: string) => {
    checkPage(7);
    doc.text(line, margin, y);
    y += 6;
  });

  if (paper.images && paper.images.length > 0) {
    y += 10;
    paper.images.forEach((imgData) => {
      const imgHeight = 80;
      checkPage(imgHeight + 10);
      try {
        const xPos = (pageWidth - 80) / 2;
        doc.addImage(imgData, 'PNG', xPos, y, 80, imgHeight);
        y += imgHeight + 10;
      } catch (e) {
        console.error("PDF Image Error", e);
      }
    });
  }

  if (paper.sources && paper.sources.length > 0) {
    checkPage(20);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(180, 140, 20);
    doc.text("BIBLIOGRAPHY & SOURCES", margin, y);
    y += 10;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 200);
    
    paper.sources.forEach(source => {
      const sourceText = `${source.title}: ${source.url}`;
      const sourceLines = doc.splitTextToSize(sourceText, textWidth);
      sourceLines.forEach((line: string) => {
        checkPage(6);
        doc.text(line, margin, y);
        y += 5;
      });
      y += 2;
    });
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by The Historian AI Agent - ${new Date(paper.timestamp).toLocaleDateString()}`, margin, doc.internal.pageSize.getHeight() - 10);

  doc.save(`${paper.title.replace(/\s+/g, '_')}_Research.pdf`);
};
